server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/** 
              Path=/api/auth/**

        - id: employee_service
          uri: http://localhost:8082
          predicates:
              - Path=/api/employees/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials,Access-Control-Allow-Origin,RETAIN_FIRST
