spring:
application:
name: employeeService

datasource:
url: jdbc:h2:mem:employee_db
driver-class-name: org.h2.Driver
username: sa
password: "00000000"

jpa:
hibernate:
ddl-auto: update
show-sql: true

h2:
console:
enabled: true
server:
port: 8082

management:
endpoints:
web:
exposure:
include: health,info
